server:
  port: 8084
spring:
  application:
    name: Ordered-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/myusers
    username: root
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: 'true'
